spring.application.name=ai-error-tracker

server.port=${PORT:8080}

# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# REDIS
spring.data.redis.url=${REDIS_URL}
spring.data.redis.password=${REDIS_PASSWORD:}

# AI
app.ai.provider=groq
app.ai.enabled=true
app.ai.groq.api-key=${GROQ_API_KEY}
app.ai.groq.base-url=https://api.groq.com/openai/v1
app.ai.groq.model=llama3-70b-8192
app.ai.groq.max-tokens=2048
app.ai.groq.temperature=0.3

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiry-hours=8

# CORS
app.cors.allowed-origins=${CORS_ORIGINS}

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# Logging
logging.level.com.errortracker=WARN
logging.level.root=ERROR


app.ai.ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
app.ai.ollama.model=${OLLAMA_MODEL:llama3}

# Rate Limiting
app.rate-limit.enabled=true


# Mail

mail.switch=${MAIL_SWITCH:false}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}

spring.mail.port=${MAIL_PORT:587}

spring.mail.username=${MAIL_USERNAME:}

spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.user.name=disabled

spring.security.user.password=disabled

spring.security.user.roles=NONE